### ISSUE TITLE
Flick SKK の設定画面が出ない

### ISSUE THREAD

**Issue by cocoatomo** [codefirst/FlickSKK#113]
Settings → Flick SKK と進んでも何も無い画面が表示される.
App Store アプリから Flick SKK を開くと「初期設定」「使い方」「ユーザー辞書」「ライセンス」というメニューが並んだ設定画面が表示される.

**Comment by cocoatomo** [comment]
Settings → FlickSKK と進んだときに、バージョン情報 ("Version 1.3.0" という文字列) が表示されるようになりました。それ以外のものは表示されないままです。

**Comment by mzp** [comment]
意図した動作です。
FlickSKKアプリ内にあるのは説明や辞書管理であり設定項目ではない、という認識で作られています。
今のFlickSKKに設定可能な項目はありません。
