### ISSUE TITLE
FlickSKK 1.3リリース準備

### ISSUE THREAD

**Issue by banjun** [codefirst/FlickSKK#115]
- [x] スクリーンショット更新: 内容はそのままで差し替え?
- [x] 使い方(html)更新: ダイナミック補完・補完スキップの追加
- [x] 紹介文(metadata.xml)更新: ↑と同じ?
- [x] What's New(metadata.xml) 更新: TestFlightの更新履歴からもってくる
- [x] リリース記事

**Comment by banjun** [comment]
審査出しました。

**Comment by banjun** [comment]
:confetti_ball:

**Comment by mzp** [comment]
:tada:
