### ISSUE TITLE
ダイナミック補完で絵文字がグレーアウトされない

### ISSUE THREAD

**Issue by leque** [codefirst/FlickSKK#133]
例えば、 FlickSKK で一度「ながい」を「永井」で変換すると、以降「なが」まで入力した時点で「永井」がグレーアウトされた状態で候補に表示されるようになります。

同様に https://raw.githubusercontent.com/uasi/skk-emoji-jisyo/master/SKK-JISYO.emoji.utf8 の辞書を追加した後、 frog で 🐸 を変換すると、以降 fr まで入力すると、候補には 🐸 と 🇫🇷 が表示されるようになりますが、このときはダイナミック補完の対象である 🐸 はグレーアウトされません。

絵文字の場合でも何らかの形でダイナミック補完であることがわかると嬉しいと思います。

![1](https://cloud.githubusercontent.com/assets/55155/8825987/0c6256e2-30be-11e5-95c4-abf3dc3fc224.PNG)
![2](https://cloud.githubusercontent.com/assets/55155/8825990/0fa6a4ca-30be-11e5-8175-808be6bb6310.PNG)

**Comment by mzp** [comment]
なるほどなー

**Comment by banjun** [comment]
![ios simulator screen shot 2015 07 27 15 49 24](https://cloud.githubusercontent.com/assets/11156/8900096/3b92497e-3477-11e5-89cf-e4edfab09de3.png)
半透明にするとこんな感じです。
通常文字のダイナミック補完の表示を，見えるグレーの値は変えずに，不透明グレーから半透明黒に変えたときの透過率にしてあります。

**Comment by leque** [comment]
:frog::+1:

**Comment by banjun** [comment]
thanks
