### ISSUE TITLE
タグを整理したい

### ISSUE THREAD

**Issue by banjun** [codefirst/FlickSKK#134]
もうAppleのTestFlightに`apple-`の修飾がなくていい時期な気がするのできれいにしたい。

`apple-testflight-x.y.z-n` → `x.y.z-n`

とリネームするのはどうでしょうか。

**Comment by mzp** [comment]
よいとおもいます

**Comment by banjun** [comment]
https://github.com/codefirst/FlickSKK/tags
タグ打ち直しました。
最初は現在時刻をcommiter dateとするタグで打ち直した(`git tag -am`)んですが，
上のページはタグのcommitter date降順で表示されるようなので，タグが指しているコミットのcommitter dateを付けました。

**Comment by mzp** [comment]
LGTM
