### ISSUE TITLE
NotesアプリのFormatting選択メニューを隠してしまい選択肢が選べない

### ISSUE THREAD

**Issue by cocoatomo** [codefirst/FlickSKK#151]
# 困っていること

NotesアプリのFormatting選択メニューを表示させると,
そのメニューよりもFlickSKKのキーボードが手前に表示されるため,
文章に形式を設定することができない.
# 再現手順
1. Notesアプリを起動
2. 新規にメモを作成
3. メモの右下に表示されているプラスを丸で囲ったボタンを押す
4. `Aa` と表示されたボタンを押す
# 期待する動作

Formatting選択メニューが表示され, 選択肢が選べること
# スクリーンショット
## デフォルトの英語キーボード

![img_1422](https://cloud.githubusercontent.com/assets/223050/17522870/8f1cf714-5e93-11e6-8362-d11f5ce5db08.PNG)
## FlickSKKのキーボード

![img_1423](https://cloud.githubusercontent.com/assets/223050/17522877/99dc12e8-5e93-11e6-9b6b-01bbcfcf46d1.PNG)

**Comment by banjun** [comment]
再現は確認しました。
おそらくアプリ側(Notes側)のキーボード避け実装の問題でしょうね‥(3rd partyキーボードだけ影響?)。
いまのところはiOS 10のNotesでは期待が持てそうな感じです。

**Comment by cocoatomo** [comment]
この挙動はiOS 10で直っており、困っていたことが解消しました。
後の対応は開発陣のバージョン対応ポリシーにお任せします。
