### ISSUE TITLE
三点リーダが MIDLINE HORIZONTAL ELLIPSIS になっている

### ISSUE THREAD

**Issue by unarist** [codefirst/FlickSKK#158]
https://github.com/codefirst/FlickSKK/blob/18b4c227b6df960b64edfbcc2bd2e1446dfc4934/FlickSKKKeyboard/KeyboardViewController.swift#L121-L122

標準キーボードや `&hellip;` など汎用的に使われている三点リーダが `…` (U+2026 HORIZONTAL ELLIPSIS) であるのに対し、FlickSKKで入力されるのは `⋯` (U+22EF MIDLINE HORIZONTAL ELLIPSIS) になっているようです。

（日本語の文章で使うことを前提に常に上下中央に表示されることが期待できる U+22EF をあえて選ぶという選択であれば、せめて選択可能になっているとうれしい）

iOS環境だと U+22EF 以降の文字列の見た目が変わってしまうこともあるようで……。

![bd225e29841f2f64](https://user-images.githubusercontent.com/705555/36651806-138e331a-1aee-11e8-8f08-a5072e0424d4.jpeg)

**Comment by mzp** [comment]
これなー。直さないといけないとは思ってるんだよなー。
