### ISSUE TITLE
辞書中の接頭辞・接尾辞(>を含むエントリ)を扱えるようにする

### ISSUE THREAD

**Issue by mzp** [codefirst/FlickSKK#24]
## エントリの例

```
>あつ /圧/
>い /委/医/
```
## 解説(ドキュメントより抜粋)

接頭辞 (prefix)、接尾辞 (suffix)の入力のために特別な方法が用意されていま す。たとえば、「し」の候補は沢山あり、「し」から「氏」を変換するのは、そのままでは 効率が悪いです。接尾辞の「し」ならば、「氏」や「市」が優先されるでしょう。

接頭辞・接尾辞は辞書の中では、`>` などで示されます。

```
し /氏/
```

というエントリがあるとき、「小林氏」を接尾辞入力を用いて、以下のよう に入力することができます。

`K` `o` `b` `a` `y` `a` `s` `h` `i`

```
▽こばやし-!-
```

`SPC`

```
▼小林-!-
```

`>`

```
小林▽>-!-
```

`s` `i`

```
小林▽>し-!-
```

`SPC`

```
小林▼氏-!-
```

`C`-`j`

```
小林氏-!-
```
## 参考文献
- http://openlab.jp/skk/registdic_info.html#midasi
- http://openlab.jp/skk/skk-manual/skk-manual-ja_5.html#SEC71

**Comment by banjun** [comment]
たぶん。
