### ISSUE TITLE
変換モードのとき "space" 表記を「変換」表記にする

### ISSUE THREAD

**Issue by cocoatomo** [codefirst/FlickSKK#61]
物理的なキーの種類ではなく, キーの意味を表示する方が良いと思います.

**Comment by mzp** [comment]
キーの意味となると「↑」ってなんだよ、ってことになりそうなので微妙ですが、標準のキーボードも空白と「次候補」で表示を切り替えているようなので、これは対応します。

**Comment by mzp** [comment]
やりました! 1.2にはいるはず。

**Comment by banjun** [comment]
これアグレッシブ候補表示 #18 の初期状態(候補選択されていない状態)でも表示してほしいです。

**Comment by mzp** [comment]
@banjun しました。確認ください。 #81

**Comment by banjun** [comment]
okです。
