### ISSUE TITLE
記号入力対応

### ISSUE THREAD

**Issue by cocoatomo** [codefirst/FlickSKK#62]
特に記号のキーでフリック入力するときに, どの方向にどの文字があるか忘れてしまうので必要だと思います.
標準で入っている日本語のテンキーキーボードと動作が揃う意味でも良いと思います.

**Comment by mzp** [comment]
記号が入力しずらいのはその通りだと思いますが、長押しで表示するよりも標準キーボードのようにキーの下のほうに記号を表示したほうがよいと思います。

![symbol](https://cloud.githubusercontent.com/assets/9650/6199556/6b4d6eb4-b48e-11e4-844b-5d1f21800d62.png)

**Comment by mzp** [comment]
#112 でやりました。 1.3のリリースをお待ちください。
