### ISSUE TITLE
キーボードを隠すボタン

### ISSUE THREAD

**Issue by unarist** [codefirst/FlickSKK#72]
![image](https://cloud.githubusercontent.com/assets/705555/5605209/00be48a6-9432-11e4-9266-1905d846fc58.jpg)
そういえばないですねこれ。

**Comment by mzp** [comment]
ないですが、標準のかなキーボードにもないし、FlickSKKとしては対応しません。
ごめんねー。

**Comment by unarist** [comment]
標準のキーボードにもあるのでは、と思ったらiPadのQWERTYキーボードでした。了解です。
