### ISSUE TITLE
記号入力KeyPad

### ISSUE THREAD

**Issue by banjun** [codefirst/FlickSKK#90]
#62 関連

現状のFlickSKKでは，

* z+hjklで←↓↑→相当のことができない
* 記号で「→」を入れたとして，標準キーボードのように「→」の変換で「←」「↓」「↑」とするのは不自然

なため，記号入力用のKeyPadを検討します。

左列のどれかフリックで記号入力用KeyPadになり，そこから例えば1キーのフリックに←↓↑→を割り当てて，z+hjkl相当とする作戦です。

**Comment by mzp** [comment]
great plan!

**Comment by banjun** [comment]
KeyPadを新設するより「123」KeyPadの空いている4方向で詰められそうという感じです。

**Comment by banjun** [comment]
現状の「123」KeyPadの配置に対してどう置くか案をまとめましょう。

```
123
456
789
(0.
```

(センター: 左上右下)

```
1: ←↑→↓
(: )[]
0: ～…
.: ,_/
```

**Comment by mzp** [comment]
セミコロンほしい

**Comment by mzp** [comment]
## 確定
### FlickSKK独自

 * 5: ↑↓←→

### 標準キーパッド由来
 
 * 9: ^|/
 * (: )[]
 * 0: ～…
 * .: ,_/

## 候補
### ペアにしたほうがよさそうな記号群

 * <>
 * {}
 * ?!
 * $￥
 * :;
 * '"

### ペアにならないけど、あったほうがよさそう
+*%@&=・

**Comment by mzp** [comment]
#112 でやりました。
