### ISSUE TITLE
"/"を含む単語の登録

### ISSUE THREAD

**Issue by sugyan** [codefirst/FlickSKK#91]
ユーザー辞書の登録で`/`を含む単語を登録すると、(おそらく辞書ファイルの区切りとして使われているため)別々の単語として複数登録されてしまうようです。

**Comment by mzp** [comment]
う、考慮していませんでした。
修正いたします。

**Comment by mzp** [comment]
https://github.com/codefirst/FlickSKK/issues/106 で修正しましたので、次のバージョンで修正されます。

**Comment by sugyan** [comment]
ありがとうございます！
