### ISSUE TITLE
▽モードで最後の1文字を消したとき▽モードを抜けない

### ISSUE THREAD

**Issue by na2co3-ftw** [codefirst/FlickSKK#96]
▽モードで最後の1文字をBackspaceで消したとき▽モードを抜けないので、
「▽あ」のように一文字入力した後にBackspaceを押すと▽モードのままシフトキーが復元されて、次に入力した文字が送り仮名になってしまいます。

**Comment by mzp** [comment]
▽モードで最後の1文字を消したときに、▽モードを抜けないのは、他のSKKと挙動を揃えるための意図した動きです。
ただ、シフトキーが復元されてしまうのは不便なので、そちらを修正します。

**Comment by banjun** [comment]
#103 入れてませんが #104 でこの問題は解決になりました。

**Comment by na2co3-ftw** [comment]
対応ありがとうございます。
